services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=mckinney_go_notes_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - go-notes-network
    command: >
      sh -c "
        ./wait-for-it.sh db:3306 -t 60 -- ./go-notes
      "
    env_file:
      - .env

  db:
    image: mysql:8.0
    container_name: go-notes-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mckinney_go_notes_db
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - go-notes-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-ppassword']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  go-notes-network:
    driver: bridge

volumes:
  db_data:
    driver: local
